server:
  port: 9103

  ########################################################
  # tomcat服务配置
  ########################################################
#  tomcat:
#    uri-encoding: UTF-8
#
#spring:
#  ########################################################
#  # HTTP请求配置
#  ########################################################
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
#      force: true
#  ########################################################
#  # freemarker配置
#  ########################################################
#  thymeleaf:
#    servlet:
#      content-type: text/html
